// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSob4AgmW40gTm522x4N5KzZIlH1Tjj6M',
    appId: '1:206814457468:web:2a8fb771a91ccb934923f9',
    messagingSenderId: '206814457468',
    projectId: 'bk-social-app',
    authDomain: 'bk-social-app.firebaseapp.com',
    storageBucket: 'bk-social-app.appspot.com',
    measurementId: 'G-27KP86MC0C',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVJTr3BQ9HZl87YstKukGQekgYVruiiDw',
    appId: '1:206814457468:ios:f20aa60e7301d2ff4923f9',
    messagingSenderId: '206814457468',
    projectId: 'bk-social-app',
    storageBucket: 'bk-social-app.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVJTr3BQ9HZl87YstKukGQekgYVruiiDw',
    appId: '1:206814457468:ios:f20aa60e7301d2ff4923f9',
    messagingSenderId: '206814457468',
    projectId: 'bk-social-app',
    storageBucket: 'bk-social-app.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSob4AgmW40gTm522x4N5KzZIlH1Tjj6M',
    appId: '1:206814457468:web:676286bfdeec0cc84923f9',
    messagingSenderId: '206814457468',
    projectId: 'bk-social-app',
    authDomain: 'bk-social-app.firebaseapp.com',
    storageBucket: 'bk-social-app.appspot.com',
    measurementId: 'G-K354ZKBVMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxCIECwBoA5GnQ0XOclQWjoa0sTC5xvKY',
    appId: '1:206814457468:android:a2eafee25356a93c4923f9',
    messagingSenderId: '206814457468',
    projectId: 'bk-social-app',
    storageBucket: 'bk-social-app.appspot.com',
  );

}